### ISSUE TITLE
Error while running

### ISSUE THREAD

**Issue by TheRealPiggyWiggy** [madprogrammer/singingmonsters-bot#10]
I tried to run this in MSYS MiniGW but it says "Fetching gem metadata from https://rubygems.org/
Fetching version metadata from https://rubygems.org/
Using bindata 2.4.1
Using daemons 1.2.5
Installing eventmachine 1.2.5 with native extensions

Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

    current directory: /usr/lib/ruby/gems/2.7.0/gems/eventmachine-1.2.5/ext
/usr/bin/ruby.exe -I /usr/lib/ruby/2.7.0 -r ./siteconf20201018-895-5jg2l3.rb extconf.rb
checking for -lcrypto... *** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
        --with-opt-dir
        --without-opt-dir
        --with-opt-include
        --without-opt-include=${opt-dir}/include
        --with-opt-lib
        --without-opt-lib=${opt-dir}/lib
        --with-make-prog
        --without-make-prog
        --srcdir=.
        --curdir
        --ruby=/usr/bin/$(RUBY_BASE_NAME)
        --with-ssl-dir
        --without-ssl-dir
        --with-ssl-include
        --without-ssl-include=${ssl-dir}/include
        --with-ssl-lib
        --without-ssl-lib=${ssl-dir}/lib
        --with-openssl-config
        --without-openssl-config
        --with-pkg-config
        --without-pkg-config
        --with-crypto-dir
        --without-crypto-dir
        --with-crypto-include
        --without-crypto-include=${crypto-dir}/include
        --with-crypto-lib
        --without-crypto-lib=${crypto-dir}/lib
        --with-cryptolib
        --without-cryptolib
/usr/lib/ruby/2.7.0/mkmf.rb:472:in `try_do': The compiler failed to generate an executable file. (RuntimeError)
You have to install development tools first.
        from /usr/lib/ruby/2.7.0/mkmf.rb:565:in `try_link0'
        from /usr/lib/ruby/2.7.0/mkmf.rb:583:in `try_link'
        from /usr/lib/ruby/2.7.0/mkmf.rb:802:in `try_func'
        from /usr/lib/ruby/2.7.0/mkmf.rb:1030:in `block in have_library'
        from /usr/lib/ruby/2.7.0/mkmf.rb:972:in `block in checking_for'
        from /usr/lib/ruby/2.7.0/mkmf.rb:362:in `block (2 levels) in postpone'
        from /usr/lib/ruby/2.7.0/mkmf.rb:332:in `open'
        from /usr/lib/ruby/2.7.0/mkmf.rb:362:in `block in postpone'
        from /usr/lib/ruby/2.7.0/mkmf.rb:332:in `open'
        from /usr/lib/ruby/2.7.0/mkmf.rb:358:in `postpone'
        from /usr/lib/ruby/2.7.0/mkmf.rb:971:in `checking_for'
        from /usr/lib/ruby/2.7.0/mkmf.rb:1025:in `have_library'
        from extconf.rb:8:in `block in check_libs'
        from extconf.rb:8:in `all?'
        from extconf.rb:8:in `check_libs'
        from extconf.rb:95:in `<main>'

To see why this extension failed to compile, please check the mkmf.log which can be found here:

  /usr/lib/ruby/gems/2.7.0/extensions/x86_64-msys/2.7.0/eventmachine-1.2.5/mkmf.log

extconf failed, exit code 1

Gem files will remain installed in /usr/lib/ruby/gems/2.7.0/gems/eventmachine-1.2.5 for inspection.
Results logged to /usr/lib/ruby/gems/2.7.0/extensions/x86_64-msys/2.7.0/eventmachine-1.2.5/gem_make.out
Using temple 0.8.0
Using tilt 2.0.8
Using multi_xml 0.6.0
Using mustermann 1.0.1
Using rack 2.0.3
Using bundler 1.12.5
An error occurred while installing eventmachine (1.2.5), and Bundler cannot
continue.
Make sure that `gem install eventmachine -v '1.2.5'` succeeds before bundling."

**Comment by madprogrammer** [comment]
Instead of trying to run it in MinGW, try running it in WSL (look up Ubuntu in Microsoft Store). Note that WSL is far superior than MinGW in terms of Unix software support, however  it's only available in Windows 10.

**Comment by madprogrammer** [comment]
MSYS MinGW is not supported, please try to use Ubuntu 20.04 LTS in WSL/WSL2 or running in VirtualBox
