### ISSUE TITLE
Guide? 

### ISSUE THREAD

**Issue by Niceghost21** [madprogrammer/singingmonsters-bot#15]
Could we maybe get a guide for installing everything like Ruby, git, bundler, and everything else needed on Ubuntu? I have tried several times now, but I seem to be having all sorts of problems with dependencies and what not. I can't ever get to the point where bundle exec ruby main.rb will work without issues. I seem to not be the only one either. Thank you!

**Comment by madprogrammer** [comment]
I've updated the installation instructions for an Ubuntu 20.04 LTS VM downloaded from Microsoft Store and running in WSL2 (Windows Subsystem for Linux 2, available since Windows 10 build 1903). You can try it. Note that the bot still crashes after logging in and getting player info, due to some new changes in the protocol.

**Comment by Niceghost21** [comment]
> I've updated the installation instructions for an Ubuntu 20.04 LTS VM downloaded from Microsoft Store and running in WSL2 (Windows Subsystem for Linux 2, available since Windows 10 build 1903). You can try it. Note that the bot still crashes after logging in and getting player info, due to some new changes in the protocol.

Thank you for updating it! Although, at the sudo apt install ruby ruby-devel ruby-bundler, I get Unable to locate package ruby-devel

**Comment by madprogrammer** [comment]
Sorry, try to change it to `ruby-dev` instead

**Comment by Niceghost21** [comment]
Perfect, but now I'm running into the same problem I was running into when I tried installing everything myself. An error occurrered while installing eventmachine (1.2.7), and Bundler can't continue. I'm using virtual box with ubuntu

**Comment by Niceghost21** [comment]
Never mind! I got it, I just needed to run sudo apt-get install build-essential first

**Comment by Niceghost21** [comment]
Alright! Im all caught up! Thanks!

**Comment by ghost** [comment]
When I try installing Ruby Bundler it pops with with an error that says "Package 'ruby-bundler' has no installation candidate"
