### ISSUE TITLE
Does this still work?

### ISSUE THREAD

**Issue by pqouist** [madprogrammer/singingmonsters-bot#19]
I just found this and haven't been able to get this to work but idk if it's because I'm doing something wrong or if it just doesn't work anymore

**Comment by LeftHandMan176** [comment]
Doesn't seem like it. I've tried it and always got a "required args missing" error when trying to auth.

I've been looking at the game's source for a few hours and i can't seem to find the auth requests

**Comment by pqouist** [comment]
> Doesn't seem like it. I've tried it and always got a "required args missing" error when trying to auth.
> 
> I've been looking at the game's source for a few hours and i can't seem to find the auth requests

**Comment by pqouist** [comment]
> Doesn't seem like it. I've tried it and always got a "required args missing" error when trying to auth.
> 
> I've been looking at the game's source for a few hours and i can't seem to find the auth requests

how were you looking at the games source code?
