### ISSUE TITLE
Still working?

### ISSUE THREAD

**Issue by Leusele** [madprogrammer/singingmonsters-bot#26]
Is this till working for Android/ios Version?
Would love to use it
And is there a Rist of getting baned?
Is BBB baning for stuff like this?

**Comment by madprogrammer** [comment]
1. This project is not maintained, and will not work with the latest client. However, even the official C# SmartFox2X client library can be used to easily program a new bot (see https://docs2x.smartfoxserver.com/GettingStarted/client-api-csharp).
2. Yes, there is a risk of getting banned for using stuff like this.

**Comment by Leusele** [comment]
Ty ✌️
