### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Niceghost21** [madprogrammer/singingmonsters-bot#4]
Please help.  I receive this error

c:/Users/cummi/onedrive/documents/singingmonsters-bot-master/smartfox.rb:140:in `<class:Term>': field 'type' is a reserved name in SmartFox2X::Term (NameError)
        from c:/Users/cummi/onedrive/documents/singingmonsters-bot-master/smartfox.rb:137:in `<module:SmartFox2X>'
        from c:/Users/cummi/onedrive/documents/singingmonsters-bot-master/smartfox.rb:5:in `<top (required)>'
        from c:/Users/cummi/onedrive/documents/singingmonsters-bot-master/proto.rb:2:in `require_relative'
        from c:/Users/cummi/onedrive/documents/singingmonsters-bot-master/proto.rb:2:in `<top (required)>'
        from main.rb:6:in `require_relative'
        from main.rb:6:in `<main>'

**Comment by madprogrammer** [comment]
Ok, I'll look into this

**Comment by madprogrammer** [comment]
This is fixed
